theme: jekyll-theme-leap-day
description: Yet another tech related mod pack!
show_downloads: true
github:
  zip_url: https://github.com/gaycookie/Fabricated/releases/latest/download/Fabricated.zip