name = "Fabricated"
author = "GayCookie"
version = "0.0.5"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4b72b32fe397607025f3fb554777de523c7229cbddb4282dbc9316abc2ef3e1"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[export]
[export.curseforge]
disable-jumploader = false
jumploader-forge-version = "36.1.4"
jumploader-version-id = 3227191
project-id = 0
