name = "Fabricated"
author = "GayCookie"
version = "0.0.7"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0212688700c332c3619dc02dcb2a9cf1b08b2f5bfb82f6bda2554ace89e4596a"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[export]
[export.curseforge]
disable-jumploader = false
jumploader-forge-version = "36.1.4"
jumploader-version-id = 3227191
project-id = 0
