name = "Fabricated"
author = "GayCookie"
version = "0.0.5"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1607d2ea9ad9c26470244ffb71ec7df49d4361cd9ed8a6227a8a36a42976a4ad"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[export]
[export.curseforge]
disable-jumploader = false
jumploader-forge-version = "36.1.4"
jumploader-version-id = 3227191
project-id = 0
