name = "Fabricated"
author = "GayCookie"
version = "0.0.5"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c148199305ab9a981b03e85a114ae40a35057cc7b832430160ac6a85eca4acf"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[export]
[export.curseforge]
disable-jumploader = false
jumploader-forge-version = "36.1.4"
jumploader-version-id = 3227191
project-id = 0
