name = "Fabricated"
author = "GayCookie"
version = "0.0.8"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49e8cbf585fe3d7ea91d1f66bcf311a723735dfe4105c2ac346b70d5d2cc200c"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[export]
[export.curseforge]
disable-jumploader = false
jumploader-forge-version = "36.1.4"
jumploader-version-id = 3227191
project-id = 0
