name = "Fabricated"
author = "GayCookie"
version = "0.0.8"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77e7ea24bcb24d03190eb441bb95c9b6f56003b471a379e65f3b5e24a7cd52df"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[export]
[export.curseforge]
disable-jumploader = false
jumploader-forge-version = "36.1.4"
jumploader-version-id = 3227191
project-id = 0
