name = "Fabricated"
author = "GayCookie"
version = "0.0.8"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cea879e440c6607cfd8ea4e3248c4d133129f8f49602b9618af94f0a9319cae3"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[export]
[export.curseforge]
disable-jumploader = false
jumploader-forge-version = "36.1.4"
jumploader-version-id = 3227191
project-id = 0
