name = "Fabricated"
author = "GayCookie"
version = "0.0.8"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25a5bc0e45e0f6e0b8f27a6afbed773496bc86a5c5750bc15b4799805643717e"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[export]
[export.curseforge]
disable-jumploader = false
jumploader-forge-version = "36.1.4"
jumploader-version-id = 3227191
project-id = 0
