name = "Fabricated"
author = "GayCookie"
version = "0.0.6"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c059ab2fea6862bf3858e56559973c69659427488888f0ee6e2dd318bb2c4855"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[export]
[export.curseforge]
disable-jumploader = false
jumploader-forge-version = "36.1.4"
jumploader-version-id = 3227191
project-id = 0
