name = "Architectury API (Fabric)"
filename = "architectury-1.10.139-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3254/874/architectury-1.10.139-fabric.jar"
hash-format = "murmur2"
hash = "3256365232"

[update]
[update.curseforge]
file-id = 3254874
project-id = 419697
release-channel = "beta"
