name = "Astromine: Discoveries"
filename = "astromine-discoveries-1.11.4+fabric-1.16.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3080/152/astromine-discoveries-1.11.4+fabric-1.16.3.jar"
hash-format = "murmur2"
hash = "919691145"

[update]
[update.curseforge]
file-id = 3080152
project-id = 405125
release-channel = "beta"
