name = "Astromine: Technologies"
filename = "astromine-technologies-1.11.4+fabric-1.16.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3080/154/astromine-technologies-1.11.4+fabric-1.16.3.jar"
hash-format = "murmur2"
hash = "3013277182"

[update]
[update.curseforge]
file-id = 3080154
project-id = 404376
release-channel = "beta"
