name = "Astromine: Core"
filename = "astromine-core-1.11.4+fabric-1.16.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3080/151/astromine-core-1.11.4+fabric-1.16.3.jar"
hash-format = "murmur2"
hash = "4221176473"

[update]
[update.curseforge]
file-id = 3080151
project-id = 405058
release-channel = "beta"
