name = "Astromine: Transportations"
filename = "astromine-transportations-1.11.4+fabric-1.16.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3080/155/astromine-transportations-1.11.4+fabric-1.16.3.jar"
hash-format = "murmur2"
hash = "4280238192"

[update]
[update.curseforge]
file-id = 3080155
project-id = 404375
release-channel = "beta"
