name = "Astromine: Complete"
filename = "astromine-1.11.5+fabric-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3170/222/astromine-1.11.5+fabric-1.16.5.jar"
hash-format = "murmur2"
hash = "1985213157"

[update]
[update.curseforge]
file-id = 3170222
project-id = 391739
release-channel = "beta"
