name = "Automated Crafting"
filename = "automated-crafting-1.3.21+MC1.16.2-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3213/741/automated-crafting-1.3.21+MC1.16.2-1.16.5.jar"
hash-format = "murmur2"
hash = "3051932793"

[update]
[update.curseforge]
file-id = 3213741
project-id = 389435
release-channel = "beta"
