name = "cAn i MiNe thIS bLOCk?"
filename = "can-i-mine-this-block-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3030/323/can-i-mine-this-block-1.0.2.jar"
hash-format = "murmur2"
hash = "3530271920"

[update]
[update.curseforge]
file-id = 3030323
project-id = 400929
release-channel = "beta"
