name = "Cardinal Components"
filename = "Cardinal-Components-API-2.7.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3226/444/Cardinal-Components-API-2.7.13.jar"
hash-format = "murmur2"
hash = "3011992435"

[update]
[update.curseforge]
file-id = 3226444
project-id = 318449
release-channel = "beta"
