name = "EZ Pipes and Stuff (EZPaS)"
filename = "ezpas-1.2.3-1.16.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3063/422/ezpas-1.2.3-1.16.2.jar"
hash-format = "murmur2"
hash = "4080944054"

[update]
[update.curseforge]
file-id = 3063422
project-id = 381973
release-channel = "beta"
