name = "FairEnchanting"
filename = "fairenchanting-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3018/132/fairenchanting-1.2.0.jar"
hash-format = "murmur2"
hash = "3093372595"

[update]
[update.curseforge]
file-id = 3018132
project-id = 359702
release-channel = "beta"
