name = "Grind Enchantments"
filename = "grind-enchantments-1.1.3+1.16.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3063/879/grind-enchantments-1.1.3+1.16.3.jar"
hash-format = "murmur2"
hash = "2181105957"

[update]
[update.curseforge]
file-id = 3063879
project-id = 379680
release-channel = "beta"
