name = "Inventory HUD+"
filename = "InventoryHUD-fabric-[1.16.2-1.16.5]-3.2.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3198/762/InventoryHUD-fabric-[1.16.2-1.16.5]-3.2.2.jar"
hash-format = "murmur2"
hash = "3155476420"

[update]
[update.curseforge]
file-id = 3198762
project-id = 357540
release-channel = "beta"
