name = "InvTrashSlot"
filename = "inv-trash-slot-1.0.2_mc1.16.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3096/258/inv-trash-slot-1.0.2_mc1.16.3.jar"
hash-format = "murmur2"
hash = "3924110440"

[update]
[update.curseforge]
file-id = 3096258
project-id = 400726
release-channel = "beta"
