name = "Kibe"
filename = "kibe-1.16.5-1.6.7-BETA.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3247/476/kibe-1.16.5-1.6.7-BETA.jar"
hash-format = "murmur2"
hash = "3342022310"

[update]
[update.curseforge]
file-id = 3247476
project-id = 388832
release-channel = "beta"
