name = "Large Fluid Tank for Fabric"
filename = "LargeFluidTank-16.1.1-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3185/781/LargeFluidTank-16.1.1-fabric.jar"
hash-format = "murmur2"
hash = "968179073"

[update]
[update.curseforge]
file-id = 3185781
project-id = 411564
release-channel = "beta"
