name = "MC Dungeons Weapons"
filename = "mcdw-3.0.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3248/20/mcdw-3.0.6.jar"
hash-format = "murmur2"
hash = "1161748395"

[update]
[update.curseforge]
file-id = 3248020
project-id = 407311
release-channel = "beta"
