name = "megane"
filename = "megane-3.1.6+1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3272/380/megane-3.1.6+1.16.5.jar"
hash-format = "murmur2"
hash = "2343260598"

[update]
[update.curseforge]
file-id = 3272380
project-id = 408118
release-channel = "beta"
