name = "Mo' Structures"
filename = "mostructures-1.1.0+mc.1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3228/456/mostructures-1.1.0+mc.1.16.5.jar"
hash-format = "murmur2"
hash = "3308548860"

[update]
[update.curseforge]
file-id = 3228456
project-id = 378266
release-channel = "beta"
