name = "Mo' Structures"
filename = "mostructures-1.1.1+mc.1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3262/2/mostructures-1.1.1+mc.1.16.5.jar"
hash-format = "murmur2"
hash = "2366619704"

[update]
[update.curseforge]
file-id = 3262002
project-id = 378266
release-channel = "beta"
