name = "Modern Industrialization"
filename = "Modern-Industrialization-0.3.15.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3232/104/Modern-Industrialization-0.3.15.jar"
hash-format = "murmur2"
hash = "2682323225"

[update]
[update.curseforge]
file-id = 3232104
project-id = 405388
release-channel = "beta"
