name = "Mouse Wheelie (Fabric)"
filename = "mousewheelie-1.6.4+mc1.16.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3197/990/mousewheelie-1.6.4+mc1.16.4.jar"
hash-format = "murmur2"
hash = "4038611977"

[update]
[update.curseforge]
file-id = 3197990
project-id = 317514
release-channel = "beta"
