name = "Reborn Core"
filename = "RebornCore-1.16-4.7.2+build.132.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3215/288/RebornCore-1.16-4.7.2+build.132.jar"
hash-format = "murmur2"
hash = "2907353222"

[update]
[update.curseforge]
file-id = 3215288
project-id = 237903
release-channel = "beta"
