name = "Reroll"
filename = "reroll-1.2.0-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3194/57/reroll-1.2.0-1.16.5.jar"
hash-format = "murmur2"
hash = "4237123400"

[update]
[update.curseforge]
file-id = 3194057
project-id = 401753
release-channel = "beta"
