name = "RSWires"
filename = "rswires-4.10.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3197/436/rswires-4.10.2.jar"
hash-format = "murmur2"
hash = "769118199"

[update]
[update.curseforge]
file-id = 3197436
project-id = 286328
release-channel = "beta"
