name = "Staff of Building"
filename = "staffofbuilding-1.2.5-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3196/484/staffofbuilding-1.2.5-1.16.5.jar"
hash-format = "murmur2"
hash = "961882257"

[update]
[update.curseforge]
file-id = 3196484
project-id = 382694
release-channel = "beta"
