name = "Tech Reborn"
filename = "TechReborn-1.16-3.8.2+build.220.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3244/621/TechReborn-1.16-3.8.2+build.220.jar"
hash-format = "murmur2"
hash = "2968780895"

[update]
[update.curseforge]
file-id = 3244621
project-id = 233564
release-channel = "beta"
