name = "Tom's Simple Storage Mod (Fabric)"
filename = "tomsstorage-1.1.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3233/109/tomsstorage-1.1.9.jar"
hash-format = "murmur2"
hash = "1458044248"

[update]
[update.curseforge]
file-id = 3233109
project-id = 396826
release-channel = "beta"
