name = "Xaero's World Map"
filename = "XaerosWorldMap_1.13.1_Fabric_1.16.5.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3249/709/XaerosWorldMap_1.13.1_Fabric_1.16.5.jar"
hash-format = "murmur2"
hash = "2872034536"

[update]
[update.curseforge]
file-id = 3249709
project-id = 317780
release-channel = "beta"
