name = "Xaero's Minimap"
filename = "Xaeros_Minimap_21.4.5_Fabric_1.16.5.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3256/945/Xaeros_Minimap_21.4.5_Fabric_1.16.5.jar"
hash-format = "murmur2"
hash = "2775118449"

[update]
[update.curseforge]
file-id = 3256945
project-id = 263420
release-channel = "beta"
